### ISSUE TITLE
ImportError exception when no pkg_resoureces module installed

### ISSUE THREAD

**Issue by ownport** [intropro/test-suites#1]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./test-suites/__main__.py", line 4, in <module>
  File "./test-suites/main.py", line 5, in <module>
ImportError: No module named pkg_resources
```

**Comment by ownport** [comment]
cannot reproduce.
